### ISSUE TITLE
TR compatibility

### ISSUE THREAD

**Issue by peterferrie** [jeremysrand/a2bejwld#2]
For memory-space reasons, I have a very tiny pretend ProDOS in TR.
In order to run Bejeweled there, I had to make a few patches:
- $BF00 (ENTRY) isn't #$4C;
- $BF6F (BITMAP) is zero (the entire array is zeroed - all memory is available);
- $BF9A (PFIXPTR) is zero but the prefix is always set;
- $BFFF (KVERSION) is not initialised, and might be zero;
- all filenames need to be in uppercase (I have no room to convert them).
We run if those checks aren't present in a TR build.

**Comment by jeremysrand** [comment]
I am afraid I can't do too much about most of the issues you highlight without ditching cc65 runtime entirely and most of the code relies on it because most of it is written in C.  But I can change the filenames to be all uppercase.  I have just pushed that change and I will try to get a build to you also.

**Comment by peterferrie** [comment]
Okay, thanks for the uppercase filename change.  I can fix the others via search/replace.
