### ISSUE TITLE
Speech: "Go" sounds a little odd!

### ISSUE THREAD

**Issue by tomcw** [jeremysrand/a2bejwld#5]
Hi Jeremy,

Here's a recording of a2bejwld v2.5 at the start of the game as the final lines fall into place and it saying "Go". This was done on real Apple II h/w with a Phasor card in Mockingboard mode (so basically the same as a Mockingboard).

As you can hear, it doesn't sound quite right.

I don't know if you have real h/w, or just use emulation for Mockingboard speech... but certainly the speech (SSI263) support in AppleWin is very crude, so it's not a great reference.

If you don't have real h/w, I'm happy to iterate with you to improve on this speech (I've not tried the other a2bejwld speech fragments yet). Or I'd be interested to know if you have real h/w and it sounds better than mine.

[Bejeweled(2.5)-phasor-trimmed.wav.zip](https://github.com/jeremysrand/a2bejwld/files/4569896/Bejeweled.2.5.-phasor-trimmed.wav.zip)

**Comment by jeremysrand** [comment]
I am using real HW and I am afraid what you sent is more or less what I hear also.  I have a Mockingboard from Reactive Micro with the speech chip in my //e which is what I am testing on.

I used the original Mockingboard tools found on the diskette from "back in the day" which had a "text to speech" program where you could experiment with speech speed, inflection and some other attributes.  But in the end, the results were all "so so".  "Excellent" sounds the worst to me.  It sounds like "excellent-ay" but I wasn't able to get it much better.

If you look at the source, you can find the binary data that represents the phases in a2bejwld/sound.c in a series of C arrays like gSpeakGood[].  If you extract this data and put it onto a A2 diskette as a binary file, you should be able to load this into the Mockingboard speech tools and then see what you get.

Or, you can try to work from the Mockingboard tools and see if you can get good output for one or all of the following phrases:

Go
Good
Excellent
Incredible
Level Complete
Get Ready
No More Moves

If you send me the binary data that the Mockingboard tools produces, I can put that into the program easily enough by changing the C arrays.

I would really appreciate some help making the speech better because it is pretty bad.  I came to the conclusion that the HW couldn't do much better than that but maybe I am not using the tools effectively.  So, if you have any suggestions or can offer help, that would be great!

**Comment by tomcw** [comment]
I'm trying (Applied Engineering's) Phasor disk's Text-to-speech routines. They struggle with the 3 phrases beginning with `G`, ie. `Go`, `Good` and `Get Ready`, but the other 4 are all fine.

But your `Go` is the best... in fact there appears to be a bug. In the emulator (AppleWin) I traced out the SSI263 accesses. For a2bejwld it looks like this:

NB. My registers are reg0-reg4 order, whereas your code is reg4-reg0 order.

```
SSI: -- -- -- 80 -- 
SSI: C0 -- -- -- -- 
SSI: -- -- -- 70 -- 

IRQ
SSI: E9 3A 88 7B E8 
ISR-end

IRQ
SSI: E6 3A 88 7B E8 
ISR-end

IRQ
SSI: 11 3A 88 7B E8 
ISR-end

IRQ
SSI: 63 3A 88 7B E8 
ISR-end

IRQ
SSI: 60 3A 88 7B E8 
ISR-end

IRQ
SSI: 00 -- -- -- -- 
SSI: -- -- -- 70 -- 
ISR-end
```

NB. The last (5th) set of reg values (60 3A 88 7B E8) is actually the 1st set from the next speech phrase! I've not looked at your code, but this could explain "Excellent-y" where the extra "y" is from "Incredible"! ;-)

**Comment by jeremysrand** [comment]
Well that is embarrassing.  I have an off by one error in the code.  Actually, I was incrementing the length by one because I thought I needed that to ensure the entire speech buffer was written to the device.  But because of that extra + 1, it actually sent the first 5 bytes of the next buffer, or whatever happened to come after that in memory.

I have put in a fix for this in a build attached (v2.6.a1).  This has a fix for both the hint problem you raised and it should address this off by one problem:

[a2bejwld.dsk.zip](https://github.com/jeremysrand/a2bejwld/files/4578731/a2bejwld.dsk.zip)

In order to more easily test it, I have added the ability to play any of the different speech samples by pressing the 1 through 7 keys when in the options menu, "o" or "O" to go to options.  So you can also play the messages without having to convince that your move is "incredible".

With this off-by-one fix present, "excellent" sound more excellent now also.  Thanks so much for finding this problem for me!  I plan to do some more testing of these changes and publish a v2.6 soon with these two fixes.

**Comment by tomcw** [comment]
That's good - an easy fix. Thanks for the updated build.

I tested phrases 1-7 (attached .wav for reference). All sounding much better now... perhaps only "Good" is questionable? I'll compare with Phasor's TTS later.

[Bejeweled(2.6.a1)-phasor-trimmed.zip](https://github.com/jeremysrand/a2bejwld/files/4580451/Bejeweled.2.6.a1.-phasor-trimmed.zip)

**Comment by tomcw** [comment]
I tried to improve on your "GOOD", but couldn't.

Attached is a wav with (in order):
- GO (a2bejwld 2.6.a1)
- GO (Phasor TTS)
- GO (Phasor TTS + some tweaks by me)
- GO (Phasor TTS + some tweaks by me)
- GOOD (a2bejwld 2.6.a1)
- GOOD (Phasor TTS)
- GOOD (Phasor TTS + some tweaks by me)
- GET READY (Phasor TTS)
- "Willy Byte in the digital dimension" (from the game of the same name - this is included just because my test code started with this)

All the Phasor TTS phrases starting with "G" sounds like a they start with a quiet "k" sound, whereas yours don't have this (so yours sound better).

Summary: what you currently have are the best (so far), so I'd say go with those.

[TestE-without-changing-DUR.zip](https://github.com/jeremysrand/a2bejwld/files/4586461/TestE-without-changing-DUR.zip)

**Comment by jeremysrand** [comment]
Thanks again for your help finding the bug in the speech playback and for trying to get some better speech parameters.  I will close this issue for now.
