### ISSUE TITLE
Allow movement key configuration

### ISSUE THREAD

**Issue by roughana** [jeremysrand/a2bejwld#7]
The IJKM is not as fluid for me as IJKL which allows three fingers to remain in place all the time and to just move one for up.
Please allow keyboard movement key configuration.

**Comment by jeremysrand** [comment]
Agreed.  I will look at adding that in a v2.7 soon.  I will need to not allow some keys to be used because they have other fixed meanings already like Q for quit, R to start a new game, O for options, H for hint and ? for instructions.  But any other key should be fair game if you want to use it for movement.

I always default to IJKM because those were the keys used in Apple Panic which I played a ton back in the day.  Thanks for the suggestion.

**Comment by jeremysrand** [comment]
Version 2.7 adds the ability to configure the keys used for movement.  I think this issue is resolved now.  Thanks for the suggestion!
